### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by HouYanShen** [pixel4r/BetterCampfire#1]
[23:42:29] [Server thread/INFO]: [BetterCampfire] Enabling BetterCampfire v1.0
[23:42:29] [Server thread/ERROR]: Error occurred while enabling BetterCampfire v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at com.pixel4r.plugin.enderice.bettercampfire.BetterCampfire.onEnable(BetterCampfire.java:14) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3729-Spigot-514cf03-818582f]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3729-Spigot-514cf03-818582f]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3729-Spigot-514cf03-818582f]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3729-Spigot-514cf03-818582f]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3729-Spigot-514cf03-818582f]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3729-Spigot-514cf03-818582f]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3729-Spigot-514cf03-818582f]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more

**Comment by franceja** [comment]
I haven't tested BetterCampfire on Spigot yet, and I have made this plugin based on PaperMc, Have you tried switching the Minecraft Server API to PaperMc? I suggest you use PaperMc rather than Spigot, but I'll fix this issue as soon as possible.

**Comment by franceja** [comment]
Since PaperMc has made many methods despatched in 1.19.4 which some of its methods have not existed in Spigot yet, or differ from Spigot. I would like to suggest you use PaperMc instead of Spigot until the next stable release or until Minecraft 1.20 has been released.

**Comment by franceja** [comment]
Since PaperMc has made many methods despatched in 1.19.4 which some of its methods have not existed in Spigot yet, or differ from Spigot. I would like to suggest you use PaperMc instead of Spigot until the next stable release or until Minecraft 1.20 has been released.
